### ISSUE TITLE
Background is not transparent?

### ISSUE THREAD

**Issue by StephenSHorton** [doceazedo/godot_wry#15]
I may misunderstand how this feature works, but I expected the space background to show up behind the WebView node with `Transparent` ticked on. (The web app CSS has the body background set to transparent as well)

Options:
![Image](https://github.com/user-attachments/assets/675be61f-d885-4168-aa92-bf6c2c31106f)
Gameplay:
![Image](https://github.com/user-attachments/assets/ed1d4900-15ea-4b0f-8c9c-2f8db13e9ec0)

**Comment by doceazedo** [comment]
first of all, tysm for using the extension and finding so many issues haha that's very helpful :)

this is because the WebView node is based on the Panel node, which has a grey texture by default. If you are using the WebView on the full screen size, you can just set the WebView transform properties to be of size 0, 0.

if you're not using it on full screen size, i think you can make the panel transparent, but i'm honestly not sure.

the default Panel background color should be fixed anyways, so i'll label this as a bug

**Comment by StephenSHorton** [comment]
I've set the WebView node's transform size to 0, 0. And I've also added a transparent style box to the panel stuff in the theme overrides. I'm still not able to get the background to be transparent.
![Image](https://github.com/user-attachments/assets/09b501cf-9230-4a59-98a5-4629c438e220)
![Image](https://github.com/user-attachments/assets/f52384da-f457-4120-ac46-e3f8a400c2d4)

I'd love to help contribute possibly and help solve this issue (if it is an issue). I noticed your [CONTRIBUTING.md](https://github.com/doceazedo/godot_wry/blob/main/CONTRIBUTING.md) file is missing. Would love to support, this is a great addon for someone like myself. I love using web styling to build UI. It's a game changer for me.

**Comment by doceazedo** [comment]
hmm, not sure what's going on... i'll dig into it on my end.

haven't created a CONTRIBUTING.md file yet (maybe a good first issue? 😅), but you're totally free to contribute however you want! if you need anything from me, just lmk.

**Comment by doceazedo** [comment]
i created a theme to override the panel style with an StyleBoxEmpty and it worked fine:

![Image](https://github.com/user-attachments/assets/14dec521-07f2-4ba6-8fbe-39ee170e1071)

![Image](https://github.com/user-attachments/assets/a8df747d-c1b8-4e5b-8470-41c453a28cf5)

i'll leave the ticket open for this workaround to not be needed

**Comment by LunarDEVde** [comment]
Same problem here.
I created a WebViewBridge vom .gd Script to C# cuz i hate .gd Script and got the weird box.
I thought i had a problem between my WebViewBridge and the plugin, but it really seems to be it's the WebView Node itself.

![Image](https://github.com/user-attachments/assets/dc64a8be-172d-4ba5-96fb-e77a5c4b929b)

![Image](https://github.com/user-attachments/assets/2b66015e-8bda-461d-ba7a-f07afd09da96)

**Comment by doceazedo** [comment]
i'm reopening this D: i tested on windows and this is still happening, which is so cursed bc we don't even extend the Panel node anymore, so it should not have a gray square there.

**Comment by LunarDEVde** [comment]
hey doce,
i also noticed the issue and i'm trying to find a solution too.

**Comment by xShader1374** [comment]
Same here, noticed the issue today trying the plugin out and can't find a fix yet :c

**Comment by xVanco** [comment]
I have also tried this plugin and the C# version. For both implementations same issue.

I could find out that you can change the default Background to change the color of the window and also the color of the "transparent" mode.

So for me this seems to be some kind of Windows specific layering problem inside the main window.

You can also set the whole godot window transparent to make it work, but you loose all background stuff (for example Sprites, etc.).

What worked for me but was pretty laggy, was to create a new transparent window in Godot and initialize the webview there. And set this window as overlay of the main window. 

So for me it seems to be a godot main window problem.

**Comment by dsh0416** [comment]
I probably fixed this issue, it is windows-related. Since the window created by Godot is with `WS_CLIPCHILDREN` which disables the window transparency. The patch uses Windows API to reenable it during the webview creation process. #24

**Comment by doceazedo** [comment]
it's indeed fixed:

![image](https://github.com/user-attachments/assets/b201e78d-64cc-42b0-9f6a-5aef7e98283c)

thank you so much once again!
